swagger: '2.0'
info:
  version: 3.0.2
  x-date: 10-30-2018
  title: health
  description: |-
  
    Example: An application service example to store health care related information.

    * TODO: elaborate this example
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Health Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/healths:
    get:
      description: Returns all healths
      operationId: get_health
      produces:
        - application/json
      responses:
        '200':
          description: health info
          schema:
            $ref: '#/definitions/Health'
    put:
      summary: Create a new health
      operationId: add_health
      parameters:
        - in: body
          name: health
          description: The new health to create
          schema:
            $ref: '#/definitions/Health'
      responses:
        '201':
          description: Created
  '/cloudmesh/health/{name}':
    get:
      description: Returns a health
      operationId: get_health_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: health info
          schema:
            $ref: '#/definitions/Health'
definitions:
  Health:
    type: object
    description: the health
    properties:
      PatientAccountNo:
        type: integer
        description: Patient account no
      FirstName:
        type: string
        description: First name
      LastName:
        type: string
        description: Last name
      Gender:
        type: string
        description: Gender preference
      BloodType:
        type: string
        description: Blood Type
