---
swagger: "2.0"
info: 
  version: "0.0.3"
  title: "Profile"
  description: >
               Profiles are used to store information about users for a specific service. Profiles can be added, removed and listed. A group in the profile can be used to groups certain users.
  termsOfService: "http://cloudmesh.org/terms/"
  contact: 
    name: "Cloudmesh Profile"
    url: https://cloudmesh-community.github.io/nist/spec/
  license: 
    name: "Apache"
host: "localhost:8080"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /cloudmesh/profile/profiles:
    get:
      tags:
      - "profile"
      description: "Returns all profiles"
      operationId: get_profile
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "profile information"
          schema: 
            $ref: "#/definitions/Profile"
    put:
      tags:
      - "profile"
      summary: "Create a new profile"
      operationId: add_profile
      parameters:
        - in: body
          name: profile
          description: "The new profile to create"
          schema:
            $ref: "#/definitions/Profile"
      responses:
        "201":
          description: Created
  /cloudmesh/profile/profiles/{uuid}:
    get:
      tags:
      - "profile"
      
      description: "Returns a the profile of a user"
      operationId: getProfileByUuid
      parameters:
        - name: uuid
          in: path
          required: true
          type: string
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "profile information"
          schema: 
            $ref: "#/definitions/Profile"
definitions:
  Profile:
    type: "object"
    #required:
    #  - "uuid"
    properties: 
      uuid:
        type: "string"
        description: a unique id for the profile
      username:
        type: "string"
        description: the username associated with the profile
      group:
        type: "string"
        description: a group this profile may be associated to
      resource:
        type: "string"
        description: a resource this profile may belong to
      context:
        type: "string"
        description: a context the profile may belong to 
      description:
        type: "string"
        description: a description for this profile
      firstname:
        type: "string"
        description: the firstanme of the profile user
      lastname:
        type: "string"
        description: the lastname of the profile user
      publickey:
        type: "string"
        description: the lastname of the profile user
      email:
        type: "string"
        description: the email of the profile user
