---
swagger: "2.0"
info: 
  version: "0.0.1"
  title: "profile"
  description: "A simple service to get cpuinfo as an example of using bin-2.0 specification and codegen"
  termsOfService: "http://bin.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
    url: https://cloudmesh-community.github.io/nist/spec/
  license: 
    name: "Apache"
host: "localhost:8080"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /cloudmesh/profile/profiles:
    get:
      tags:
      - "profile"
      description: "Returns all general description users"
      operationId: get_profile
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "profile info"
          schema: 
            $ref: "#/definitions/Profile"
    put:
      tags:
      - "profile"
      summary: "Create a new profile"
      operationId: add_profile
      parameters:
        - in: body
          name: profile
          description: "The new profile to create"
          schema:
            $ref: "#/definitions/Profile"
      responses:
        "201":
          description: Created
  /cloudmesh/profile/profiles/{uuid}:
    get:
      tags:
      - "profile"
      description: "Returns a general description of a user"
      operationId: getProfileByUuid
      parameters:
        - name: uuid
          in: path
          required: true
          type: string
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "profile info"
          schema: 
            $ref: "#/definitions/Profile"
definitions:
  Profile:
    type: "object"
    #required:
    #  - "uuid"
    properties: 
      uuid:
        type: "string"
      username:
        type: "string"
      group:
        type: "string"
      resource:
        type: "string"
      context:
        type: "string"
      description:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      publickey:
        type: "string"
      email:
        type: "string"
