---
swagger: "2.0"
info:
  version: 3.0.3
  x-date: 11-06-2018
  title: "Profile"
  description: |-
  
    Profiles are used to store information about users. User
    information can be reused in other services. Profiles are useful to
    create virtual organization the depend on user data.  Profiles can
    be added, removed and listed. A group in the profile can be used
    to augment users to be part of one or more groups.  A number of
    roles can specify a specific role of a user.
    
    Terminology

    * *Group*: A Person with profile can be part of a Group
    * *Role*: A person with profile can have a role within that Group


  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: "Cloudmesh Profile"
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: "Apache"
host: "localhost:8080"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /cloudmesh/profile/profile:
    get:
      tags:
        - "profile"
      description: "Returns all profiles"
      operationId: get_profile
      produces:
        - "application/json"
      responses:
        "200":
          description: "profile information"
          schema:
            $ref: "#/definitions/Profile"
    put:
      tags:
        - "profile"
      summary: "Create a new profile"
      description: "Create a new profile"      
      operationId: add_profile
      parameters:
        - in: body
          name: profile
          description: "The new profile to create"
          schema:
            $ref: "#/definitions/Profile"
      responses:
        "201":
          description: Created
  /cloudmesh/profile/profile/{uuid}:
    get:
      tags:
        - "profile"
      description: "Returns the profile of a user while looking it up with the UUID"
      operationId: getProfileByUuid
      parameters:
        - name: uuid
          in: path
          required: true
          type: string
      produces:
        - "application/json"
      responses:
        "200":
          description: "profile information"
          schema:
            $ref: "#/definitions/Profile"
definitions:
  Profile:
    type: "object"
    properties:
      uuid:
        type: "string"
        description: A unique id for the profile
      username:
        type: "string"
        description: The unique username associated with the profile
      group:
        type: array
        description: A list of groups that are associated to the profile
        items:
          type: "string"
      role:
        type: array
        description: A list of groups that are associated to the profile
        items:
          type: "string"
      resource:
        type: array
        description: A list of resources the profile has access to
        items:
          type: "string"
      description:
        type: "string"
        description: A description for this profile
      firstname:
        type: "string"
        description: The firstanme of the profile user
      lastname:
        type: "string"
        description: The lastname of the profile user
      publickey:
        type: "string"
        description: The lastname of the profile user
      email:
        type: "string"
        description: The email of the profile user
