---
swagger: "2.0"
info:
  description: "A simple service to get cpuinfo as an example of using bin-2.0 specification\
    \ and codegen"
  version: "0.0.1"
  title: "profile"
  termsOfService: "http://bin.io/terms/"
  contact:
    name: "Cloudmesh REST Service Example"
    url: "https://cloudmesh-community.github.io/nist/spec/"
  license:
    name: "Apache"
host: "localhost:8080"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /cloudmesh/profile/profiles:
    get:
      tags:
      - "profile"
      description: "Returns all general description users"
      operationId: "get_profile"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "profile info"
          schema:
            $ref: "#/definitions/Profile"
      x-swagger-router-controller: "swagger_server.controllers.profile_controller"
    put:
      tags:
      - "profile"
      summary: "Create a new profile"
      operationId: "add_profile"
      parameters:
      - in: "body"
        name: "profile"
        description: "The new profile to create"
        required: false
        schema:
          $ref: "#/definitions/Profile"
      responses:
        201:
          description: "Created"
      x-swagger-router-controller: "swagger_server.controllers.profile_controller"
  /cloudmesh/profile/profiles/{uuid}:
    get:
      tags:
      - "profile"
      description: "Returns a general description of a user"
      operationId: "get_profile_by_uuid"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "profile info"
          schema:
            $ref: "#/definitions/Profile"
      x-swagger-router-controller: "swagger_server.controllers.profile_controller"
definitions:
  Profile:
    type: "object"
    properties:
      uuid:
        type: "string"
      username:
        type: "string"
      group:
        type: "string"
      resource:
        type: "string"
      context:
        type: "string"
      description:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      publickey:
        type: "string"
      email:
        type: "string"
    example:
      firstname: "firstname"
      resource: "resource"
      context: "context"
      publickey: "publickey"
      description: "description"
      uuid: "uuid"
      email: "email"
      username: "username"
      group: "group"
      lastname: "lastname"
