---
swagger: "2.0"
info: 
  version: "0.0.1"
  title: "Virtual Cluster"
  description: "Virtual Cluster example"
  termsOfService: "https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt"
  contact: 
    name: "Cloudmesh REST Service Example"
    url: https://cloudmesh-community.github.io/nist/spec/
  license: 
    name: "Apache"
host: "localhost:8080"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /cloudmesh/virtualcluster/virtualclusters:
    get:
      tags:
      - "virtualcluster"
      description: "Returns all virtualclusters"
      operationId: get_virtualcluster
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "profile info"
          schema: 
            $ref: "#/definitions/VirtualCluster"
    put:
      tags:
      - "virtualcluster"
      summary: "Create a new virtualcluster"
      operationId: add_virtualcluster
      parameters:
        - in: body
          name: virtualcluster
          description: "The new virtualcluster to create"
          schema:
            $ref: "#/definitions/VirtualCluster"
      responses:
        "201":
          description: Created
  /cloudmesh/virtualcluster/virtualclusters/{virtualclustername}:
    get:
      tags:
      - "virtualcluster"
      description: "Returns a virtualcluster by its name"
      operationId: getVcByName
      parameters:
        - name: virtualclustername
          in: path
          required: true
          type: string
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "virtualcluster info"
          schema: 
            $ref: "#/definitions/VirtualCluster"
  /cloudmesh/virtualcluster/virtualclusters/{virtualclustername}/fe:
    get:
      tags:
      - "virtualcluster"
      description: "Returns the front-end node info of the specified virtualcluster"
      operationId: getVcFeByName
      parameters:
        - name: virtualclustername
          in: path
          required: true
          type: string
      produces:
        - "application/json"
      responses:
        "200":
          description: "virtualcluster front-end info"
          schema:
            $ref: "#/definitions/Node"
  /cloudmesh/virtualcluster/virtualclusters/{virtualclustername}/{nodename}:
    get:
      tags:
      - "virtualcluster"
      description: "Returns the specified node info of the specified virtualcluster"
      operationId: getVcNodeByName
      parameters:
        - name: virtualclustername
          in: path
          required: true
          type: string
        - name: nodename
          in: path
          required: true
          type: string
      produces:
        - "application/json"
      responses:
        "200":
          description: "virtualcluster node info"
          schema:
            $ref: "#/definitions/Node"
definitions:
  VirtualCluster:
    type: "object"
    properties:
      name:
        description: The name of the virtual cluster
        type: "string"
      description:
        type: "string"
        description: test
      nnodes:
        type: "integer"
        description: test        
      owner:
        type: "string"
        description: test        
      fe:
        description: test      
        $ref: "#/definitions/Node"
      nodes:
        description: test      
        type: array
        items:
          $ref: "#/definitions/Node"
  Node:
    type: "object"
    properties:
      name:
        type: "string"
      state:
        type: "string"
      ncpu:
        type: "integer"
      ram:
        type: "string"
      disk:
        type: "string"
      nics:
        type: "array"
        items:
          $ref: "#/definitions/NIC"
  NIC:
    type: "object"
    properties:
      mac:
        type: "string"
      ip:
        type: "string"
