swagger: '2.0'
info:
  version: 3.1.0
<<<<<<< HEAD
  x-status: defined
  x-date: 01-29-2019  
  title: Database
  description: |-
  
    A database could have a name, an endpoint (e.g., host, port),
    and a protocol used (e.g., SQL, MongoDB, ...).

=======
  x-date: 01-29-2019
  x-status: defined
  title: database
  description: |-
  
    A database could have a name, an endpoint (e.g., host, port),
    and a protocol used (e.g., SQL, mongo).
    
>>>>>>> bcc466b0301e60fce4d7bf1b594ba5e66a6eff77
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/database:
    get:
      description: Returns all databases
      operationId: get_database
      produces:
        - application/json
      responses:
        '200':
          description: database info
          schema:
            $ref: '#/definitions/Database'
    put:
<<<<<<< HEAD
      summary: Create a new database
      description: Create a new database      
=======
      description: Create a new database entry
>>>>>>> bcc466b0301e60fce4d7bf1b594ba5e66a6eff77
      operationId: add_database
      parameters:
        - in: body
          name: database
          required: true
          description: The new database record to create
          schema:
            $ref: '#/definitions/Database'
      responses:
        '201':
          description: Created
  '/cloudmesh/database/{name}':
    get:
      description: Returns a database by name
      operationId: get_database_by_name
      parameters:
        - name: name
          description: name of the database
          in: path
          required: true
          type: string
          description: The name of the database
      produces:
        - application/json
      responses:
        '200':
          description: database info
          schema:
            $ref: '#/definitions/Database'
definitions:
  Database:
    type: object
    description: This defines a database object as an entry
    properties:
      name:
        type: string
        description: name of the database
      description:
        type: string
        description: description of the database
      endpoint:
        type: string
        description: endpoint of the database
      kind:
        type: string
        description: the kind of the database
