swagger: '2.0'
info:
  version: 3.1.0
<<<<<<< HEAD
  x-status: defined
  x-date: 01-29-2019  
  title: Default
=======
  x-date: 01-29-2019
  x-status: defined
  title: default
>>>>>>> bcc466b0301e60fce4d7bf1b594ba5e66a6eff77
  description: |-
  
    A default is a special variable that has a context associated with
    it. This allows one to define values that can be easily retrieved
    based on the associated context. For example, a default could be
    the image name for a cloud where the context is defined by the
<<<<<<< HEAD
    cloud name. In addition to the context we also specify the service
    name as a service could have multiple context.
=======
    cloud name.
>>>>>>> bcc466b0301e60fce4d7bf1b594ba5e66a6eff77
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/default:
    get:
      description: Returns all defaults
      operationId: get_default
      produces:
        - application/json
      responses:
        '200':
          description: default info
          schema:
            $ref: '#/definitions/Default'
    put:
<<<<<<< HEAD
      summary: Create a new default
      description: Create a new default      
=======
      description: Create a new default
>>>>>>> bcc466b0301e60fce4d7bf1b594ba5e66a6eff77
      operationId: add_default
      parameters:
        - in: body
          name: default
          required: true
          description: The new default to create
          schema:
            $ref: '#/definitions/Default'
      responses:
        '201':
          description: Created
  '/cloudmesh/default/{name}':
    get:
      description: Returns a default
      operationId: get_default_by_name
      parameters:
        - name: name
          description: name of the default
          in: path
          required: true
          type: string
          description: The name of the default
      produces:
        - application/json
      responses:
        '200':
          description: default info
          schema:
            $ref: '#/definitions/Default'
definitions:
  Default:
    type: object
    description: the defaults
    properties:
      name:
        type: string
        description: The name of the default
      value:
        type: string
        description: The type of the default
      kind:
        type: string
        description: The value of the default
