---
swagger: "2.0"
info: 
  version: "0.0.1"
  title: "key"
  description: "A simple service to get cpuinfo as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh/key"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /keys:
    get: 
      description: "Returns all general description keys"
      operationId: get_key
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "key info"
          schema: 
            $ref: "#/definitions/Key"
    put:
      summary: "Create a new key"
      operationId: add_key
      parameters:
        - in: body
          name: key
          description: "The new key to create"
          schema:
            $ref: "#/definitions/Key"
      responses:
        "201":
          description: Created
  /key/{name}:
    get: 
      description: "Returns a general description of a key"
      operationId: getKeyByName
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "key info"
          schema: 
            $ref: "#/definitions/Key"
definitions:
  Key:
    type: "object"
    properties: 
      name:
        type: "string"
      description:
        type: "string"
      value:
        type: "string"
      type:
        type: "string"
