swagger: "2.0"
info:
  version: "3.1.1"
  x-status: defined
  x-date: 02-15-2019
  title: Cloudmesh NIST BDRA Specification API Example
  description: |-

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json