swagger: "2.0"
info:
  version: 3.0.1
  title: nic
  description: |-
  
    A service to store nic, value, type information. All of them are
    stored as Strings.

    * TODO: assign and improve
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/nics:
    get:
      description: Returns all nics
      operationId: cloudmesh.nic.get
      produces:
        - application/json
      responses:
        '200':
          description: nic info
          schema:
            $ref: '#/definitions/Nic'
    put:
      summary: Create a new nic
      operationId: cloudmesh.nic.put
      parameters:
        - in: body
          name: nic
          description: The new nic to create
          schema:
            $ref: '#/definitions/Nic'
      responses:
        '201':
          description: Created
  '/cloudmesh/nic/{name}':
    get:
      description: Returns a nic
      operationId: cloudmesh.nic.get_by_name
      parameters:
        - name: name
          description: Get nic info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: nic info
          schema:
            $ref: '#/definitions/Nic'
definitions:
  Nic:
    type: object
    description: the nic
    properties:
      name:
        type: string
        description: name of the nic
      kind:
        type: string
        description: kind of the nic, such as wireless
      mac:
        type: string
        description: the mac address
      ip:
        type: string
        description: the ip address
      mask:
        type: string
        description: the network mask
      broadcast:
        type: string
        description: the broadcast address
      gateway:
        type: string
        description: the gateway address
      mtu:
        type: integer
        description: the mtu
      bandwidth:
        type: integer
        description: the bandwidth in bps
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'

