swagger: "2.0"
info:
  version: 3.1.1
  x-status: defined
  x-date: 02-15-2019
  title: Key
  description: |-
  
    Many services and frameworks use Secure Shell (SSH) keys to
    authenticate. This service allows the convenient storage of the
    public keys.

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh REST
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/publickey:
    get:
      description: Returns all public keys
      operationId: publickey.get
      produces:
        - application/json
      responses:
        '200':
          description: public key information
          schema:
            $ref: '#/definitions/Key'
    put:
      summary: Put a new public key into the public key store
      description: Put a new public key into the public key store
      operationId: publickey.put
      parameters:
        - in: body
          name: The name of the public key
          description: The public key to be uploaded
          schema:
            $ref: '#/definitions/Publickey'
      responses:
        '201':
          description: Created
  '/cloudmesh/publickey/{name}':
    get:
      description: Returns a public key by name
      operationId: publickey.get_by_name
      parameters:
        - name: The name of the public key
          in: path
          required: true
          type: string
          description: The name of the public key
      produces:
        - application/json
      responses:
        '200':
          description: public key information
          schema:
            $ref: '#/definitions/Publickey'
definitions:
  Publickey:
    type: object
    description: the public key
    properties:
      name:
        type: string
        description: The name of the public key
      value:
        type: string
        description: The value of the public key
      kind:
        type: string
        description: The key kind such as rsa, dsa
      comment:
        type: string
        description: A comment for the public key
      uri:
        type: string
        description: The uri of the public key if any
      fingerprint:
        type: string
        description: The fingerprint of the public key
      timestamp:
        description: timestamps associated with the resource
        $ref: 'timestamp.yaml#/definitions/Timestamp'
